version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
